name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linux:
    runs-on: ${{ matrix.runner_label }}
    strategy:
      matrix:
        runner_label: ["self-hosted", "Linux", "Arm64", "x86"]
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
